### ISSUE TITLE
 Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by carsonpowers** [inooid/react-redux-card-game#60] opened 2017-07-24 00:17 UTC
On Windows > npm install > npm start >

"error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style"

Solution:

react-redux-card-game (directory) > .eslintrc (file) > rules > add ["linebreak-style": 0,](http://i.imgur.com/FrCMXSU.png?1)

**Comment by inooid** [comment] 2017-07-24 09:45
@sabrick Interesting. I never heard or seen anyone with this problem. Will investigate. Is it only an ESLint error or does it actually not install?

**Comment by carsonpowers** [comment] 2017-07-24 13:10
I updated my comment slightly. "npm install" runs fine. The error occurs with "npm start". Here's a screenshot of the [start of the error block.](http://i.imgur.com/cZakv5m.png?1)

I suspect this is a Windows issue? Just a guess.

**Comment by glambert** [comment] 2017-08-01 14:02
What about that warning? 

> WARNING in webpack: Using NoErrorsPlugin is deprecated. Use NoEmitOnErrorsPlugin instead.

**Comment by inooid** [comment] 2017-08-01 14:03
@ls-guillaume-lambert Pretty sure that's not related. Nonetheless, I should update webpack 👍 
 
I assume the issue is happening on Windows due to the way git automatically formats the files when pulling a repo, but I am not sure.

**Comment by glambert** [comment] 2017-08-01 14:17
The culprit is in this webpack rule: https://github.com/inooid/react-redux-card-game/blob/master/webpack/webpack.config.js#L31-L36

Look at this: http://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems

**Comment by inooid** [comment] 2017-08-01 14:23
Thanks for the links @ls-guillaume-lambert, much appreciated! The webpack rule is definitely a little overkill. Warning seems to be good enough, but completely stopping the build is definitely too much 👍 .
 
For the ESLint link, I'll look into the `.gitattributes` file that seems really interesting. I'll try and figure out whether it's a local file or a file that's checked into the repo 🤔

**Comment by inooid** [comment] 2018-04-10 20:23
After investigating this should be fixed at the user. ESLint is correctly warning against the wrong kind of linebreaks 👍

**Closed as completed by inooid** 2018-04-10 20:23 UTC
Labels: wontfix
